name: Deploy website to S3

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: portfolio-website/package-lock.json

      - name: Install dependencies
        working-directory: portfolio-website
        run: npm ci

      - name: Build website
        working-directory: portfolio-website
        run: npm run build

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::058264130979:role/GitHubDanielWebsiteDeploy
          aws-region: af-south-1

      - name: Upload website to S3
        run: aws s3 sync portfolio-website/out/ s3://danielolafisoye.com/